version: "3.8"
services:
  moneyhand_tests:
    build:
      context: .
      target: dev
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: "password"


  cli:
    build:
      context: .
      target: cli
    depends_on:
      - postgresql
