version: "3.8"
services:
  tests:
    build:
      context: .
      target: tests
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: "password"

    ports:
    - 5432:5432

  cli:
    build:
      context: .
      target: cli
    depends_on:
      - postgresql

  telegram_bot:
    build:
      context: .
      target: telegram_bot
    depends_on:
      - postgresql
    entrypoint: /bin/run_telegram_bot
    env_file:
      - conf/config.env
